name: Deploy mouse-tracker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts

    - name: Upload backend to ${{ secrets.DEPLOY_BACKEND_PATH }}
      run: |
        rsync -az --delete -e "ssh -i ~/.ssh/id_ed25519" ./backend/ \
          ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:${{ secrets.DEPLOY_BACKEND_PATH }}

    - name: Restart backend service
      run: |
        ssh -i ~/.ssh/id_ed25519 ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << EOF
          cd ${{ secrets.DEPLOY_BACKEND_PATH }}
          docker compose up -d --build
        EOF

    - name: Upload frontend to ${{ secrets.DEPLOY_FRONTEND_PATH }}
      run: |
        rsync -az --delete -e "ssh -i ~/.ssh/id_ed25519" ./frontend/ \
          ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:${{ secrets.DEPLOY_FRONTEND_PATH }}
